Write a function to compute 5/0 and use try/except to catch the exceptions

In [3]:
class Exceptions:
    def __init__(self,num1,num2):
        self.num1=num1
        self.num2=num2
    def func(self):
        try:
            div=self.num1/self.num2
            return div
        except:
            return "Number cannot be divided by 0"
num1,num2=map(int,input("Enter 2 number:").split(','))

f=Exceptions(num1,num2)
print(f.func())

Enter 2 number:5,0
Number cannot be divided by 0


Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [11]:
class sentences:
    def __init__(self,subjects,verbs,obj):
        self.subjects=subjects
        self.verbs=verbs
        self.obj=obj
    
    def sentenceConstruct(self):
        return [[s,v,o] for s in self.subjects for v in self.verbs for o in self.obj]
                    
subjects=["Americans","Indians"]
verbs=["play","watch"]
obj=["Baseball","Cricket"]

s=sentences(subjects,verbs,obj)
concatenateSentences=s.sentenceConstruct()
for sen in concatenateSentences:
    print("{} {} {}".format(sen[0],sen[1],sen[2]))


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [21]:
import numpy as np

class vector:
    def __init__(self,l,N):
        self.l=l
        self.N=N
    def matrix(self):
        return np.vander(l,N,increasing=False)
    
l=np.array(list(map(int,input("Enter numbers with comma separated:").split(','))))
N=int(input("Enter number of columns: "))

m=vector(l,N)
print(m.matrix())

Enter numbers with comma separated:1,2,3,4
Enter number of columns: 3
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [23]:
l=list(map(int,input("Enter numbers with comma separated:").split(',')))
N=int(input("Enter number of columns: "))
print([j**(N-i-1) for j in l for i in range(N)])

Enter numbers with comma separated:1,2,3,4
Enter number of columns: 3
[1, 1, 1, 4, 2, 1, 9, 3, 1, 16, 4, 1]
